// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import { Task } from '../../src/types/task';

export function Greet(arg1: string): Promise<string>;

export function LoadTasks(): Promise<Task[]>;

export function SaveTasks(tasks: Task[]): Promise<void>;

export function UpdateTask(task: Task): Promise<void>;

export function MoveTask(taskId: number, newStatus: string): Promise<void>;

export function GetTasksByStatus(status: string): Promise<Task[]>;
