// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTasksByStatus(arg1) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1);
}

export function LoadTasks() {
  return window['go']['main']['App']['LoadTasks']();
}

export function MoveTask(arg1, arg2) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2);
}

export function SaveTasks(arg1) {
  return window['go']['main']['App']['SaveTasks'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
