// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1, arg2) {
  return window['go']['main']['App']['AddRepository'](arg1, arg2);
}

export function ApproveTask(arg1) {
  return window['go']['main']['App']['ApproveTask'](arg1);
}

export function FindRepositories(arg1) {
  return window['go']['main']['App']['FindRepositories'](arg1);
}

export function GetAgentStatus() {
  return window['go']['main']['App']['GetAgentStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRepositories() {
  return window['go']['main']['App']['GetRepositories']();
}

export function GetTasksByStatus(arg1) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1);
}

export function LoadPlan() {
  return window['go']['main']['App']['LoadPlan']();
}

export function LoadTasks() {
  return window['go']['main']['App']['LoadTasks']();
}

export function MoveTask(arg1, arg2) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function RejectTask(arg1) {
  return window['go']['main']['App']['RejectTask'](arg1);
}

export function RemoveRepository(arg1) {
  return window['go']['main']['App']['RemoveRepository'](arg1);
}

export function SavePlan(arg1) {
  return window['go']['main']['App']['SavePlan'](arg1);
}

export function SaveTasks(arg1) {
  return window['go']['main']['App']['SaveTasks'](arg1);
}

export function SetActiveRepository(arg1) {
  return window['go']['main']['App']['SetActiveRepository'](arg1);
}

export function StartTerminalSession() {
  return window['go']['main']['App']['StartTerminalSession']();
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function ValidateRepositoryPath(arg1) {
  return window['go']['main']['App']['ValidateRepositoryPath'](arg1);
}
